spring:
  datasource:
    url: jdbc:mysql://localhost/catalog?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: password

jpa:
  repositories:
    base-package: com.itn.mapper.dao
  show-sql: true